services:
  pbdm_app:
    build: .
    environment:
      FLASK_SECRET_KEY: pbdm_secret_key
      PYODK_CONFIG_FILE: /run/secrets/pyodk_config
    image: istride/pbdm_app:latest
    ports:
      - "8000:8000"
    secrets:
      - pyodk_config

secrets:
  pyodk_config:
    file: pyodk_config.toml
